name: Build and Release - Website

defaults:
    run:
      working-directory: src/website

permissions:
  contents: write
  actions: read

on:
  push:
    branches:
      - main
    paths:
      - 'src/website/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          CI: true

      - name: Archive Production Artifact
        uses: actions/upload-artifact@v3
        with:
          name: website
          path: |
            build/website/**

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: website
          path: build/website

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_id }}
          release_name: Release ${{ github.run_id }}
          draft: false
          prerelease: false
          body: "Release of build ${{ github.run_id }}"
          commitish: ${{ github.sha }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/website
          asset_name: website.zip
          asset_content_type: application/zip
