name: Build and Release - Worker

permissions:
  contents: write
  actions: read

on:
  push:
    branches:
      - main
    paths:
      - 'src/worker/**'
  workflow_dispatch:

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
  
        - name: Set up Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '20'
  
        - name: Install Dependencies
          run: npm install
          working-directory: src/worker
  
        - name: Build
          run: npm run build
          working-directory: src/worker
          env:
            CI: true
  
        - name: Zip Build Artifacts
          run: zip -r worker.zip build/worker
  
        - name: Archive Production Artifact
          uses: actions/upload-artifact@v3
          with:
            name: worker
            path: worker.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
  
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: website
          path: build/worker

      - name: List files in build/worker
        run: ls -R build/worker
  
      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          files: build/worker/**
          tag_name: ${{ github.run_id }}
          name: node-teslausb-worker-${{ github.run_id }}
          body: "Release of build ${{ github.run_id }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
